### ISSUE TITLE
ModuleNotFoundError: No module named 'libs.lib'

### ISSUE THREAD

**Issue by ccenyo** [szmania/mega_manager#5]
i have installed megamanager by running python setup.py install but i amgetting this error while running megamanger : 

Traceback (most recent call last):
  File "C:\Users\Cenyo\Documents\python\Scripts\megamanager-script.py", line 11, in <module>
    load_entry_point('megamanager==0.0.2', 'console_scripts', 'megamanager')()
  File "C:\Users\Cenyo\Documents\python\lib\site-packages\pkg_resources\__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "C:\Users\Cenyo\Documents\python\lib\site-packages\pkg_resources\__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "C:\Users\Cenyo\Documents\python\lib\site-packages\pkg_resources\__init__.py", line 2443, in load
    return self.resolve()
  File "C:\Users\Cenyo\Documents\python\lib\site-packages\pkg_resources\__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "C:\Users\Cenyo\Documents\python\lib\site-packages\megamanager\__init__.py", line 1, in <module>
    from .account import Account
  File "C:\Users\Cenyo\Documents\python\lib\site-packages\megamanager\account.py", line 9, in <module>
    from libs.lib import Lib
ModuleNotFoundError: No module named 'libs.lib'

could you help me please?

**Comment by ChrisMwai** [comment]
Having the same issue. No fix?

**Comment by ochen1** [comment]
I fixed by uncommenting the lines inside libs/__init__.py and then changing libs/compress_images_lib.py to from .lib import Lib.
